### ISSUE TITLE
Tak ! 

### ISSUE THREAD

**Issue by ebroutin-camping** [victorgabillon/chipiron#3]
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ebroutin/perso/chipiron.vico/src/players/player_thread.py", line 32, in run
    move = self.game_player.select_move(board)
  File "/home/ebroutin/perso/chipiron.vico/src/players/game_player.py", line 13, in select_move
    best_move = self._player.select_move(board)
  File "/home/ebroutin/perso/chipiron.vico/src/players/player.py", line 34, in select_move
    best_move = self.main_move_selector.select_move(board)
  File "/home/ebroutin/perso/chipiron.vico/src/players/treevaluebuilders/tree_and_value_player.py", line 113, in select_move
    self.tree_explore(board)
  File "/home/ebroutin/perso/chipiron.vico/src/players/treevaluebuilders/tree_and_value_player.py", line 79, in tree_explore
    self.tree.add_root_node(board)
  File "/home/ebroutin/perso/chipiron.vico/src/players/treevaluebuilders/trees/move_and_value_tree.py", line 53, in add_root_node
    self.root_node = self.find_or_create_node(board, None, self.tree_root_half_move, None)
AttributeError: 'RecurZipfBaseTree' object has no attribute 'tree_root_half_move'
Oops!  Doubleclicked?  Try again...

**Comment by victorgabillon** [comment]
solved gracefully!
