### ISSUE TITLE
one_match  manque /home/victor/stockfish_13_linux_x64/stockfish_13_linux_x64

### ISSUE THREAD

**Issue by lezca** [victorgabillon/chipiron#9]
➜  chipiron git:(build_fixes) python chipiron/main-chipiron.py one_match --config_file_name chipiron/scripts/one_match/exp_options.yaml
RAM memory % used: 21.1
Here are the command line arguments of the script {'config_file_name': 'chipiron/scripts/one_match/exp_options.yaml'}
Here are the yaml file arguments of the script {'seed': 11, 'gui': True, 'file_name_player_one': 'RecurZipfBase4.yaml', 'file_name_player_two': 'Human.yaml', 'file_name_match_setting': 'setting_duda.yaml'}
Here are the merged arguments of the script {'profiling': False, 'config_file_name': 'chipiron/scripts/one_match/exp_options.yaml', 'seed': 11, 'gui': True, 'file_name_player_one': 'RecurZipfBase4.yaml', 'file_name_player_two': 'Human.yaml', 'file_name_match_setting': 'setting_duda.yaml'}
Successfully created the directory chipiron/scripts/one_match/one_match_outputs/Sunday-02-06-2022--23:03:07:891378 
Successfully created the directory chipiron/scripts/one_match/one_match_outputs/Sunday-02-06-2022--23:03:07:891378/games 
RAM memory % used: 21.1
RAM memory % used: 21.1
[Errno 17] File exists: 'chipiron/data/players/board_evaluators/nn_pytorch/nn_pp2d2_2/base'
Creation of the directory chipiron/data/players/board_evaluators/nn_pytorch/nn_pp2d2_2/base failed
load_or_init_weights
loading the existing param file
{'name': 'RecurZipfBase4', 'type': 'TreeAndValue', 'tree_builder': {'type': 'RecurZipfBase', 'move_explorer_priority': 'priority_best', 'opening_type': 'all_children', 'move_selection_rule': {'type': 'almost_equal_logistic', 'temperature': 2}, 'stopping_criterion': {'name': 'tree_move_limit', 'tree_move_limit': 300}}, 'board_evaluator': {'type': 'neural_network', 'neural_network': {'nn_type': 'pp2d2_2', 'nn_param_folder_name': 'base'}, 'syzygy_evaluation': True}, 'syzygy_play': True}
{'type': 'Human', 'name': 'Human', 'syzygy_play': False}
player one is  RecurZipfBase4
player two is  Human
Playing the match
args_game {'displayPositionOption': False, 'verbose': False, 'secondsPerMoveWhite': 2, 'secondsPerMoveBlack': 10, 'each_player_has_its_own_thread': True, 'starting_position': {'type': 'fromFile', 'options': {'file_name': 'Board1.text'}}}
subsccribers [<AutoProxy[Queue] object, typeid 'Queue' at 0x7f769c8c0df0>]
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lezca/workspace/chipiron/chipiron/src/games/match_manager.py", line 38, in play_one_match
    game_results = self.launch_game(player_color_to_id, args_game, game_number)
  File "/home/lezca/workspace/chipiron/chipiron/src/games/match_manager.py", line 48, in launch_game
    game_manager = self.game_manager_factory.create(args_game, player_color_to_id)
  File "/home/lezca/workspace/chipiron/chipiron/src/games/match_factories.py", line 173, in create
    board_evaluator = self.game_manager_board_evaluator_factory.create()
  File "/home/lezca/workspace/chipiron/chipiron/src/games/match_factories.py", line 59, in create
    board_evaluator = BoardEvaluator2()
  File "/home/lezca/workspace/chipiron/chipiron/src/games/match_factories.py", line 96, in __init__
    self.evaluation = Stockfish()
  File "/home/lezca/workspace/chipiron/chipiron/src/players/boardevaluators/stockfish_evaluation.py", line 7, in __init__
    self.engine = chess.engine.SimpleEngine.popen_uci("/home/victor/stockfish_13_linux_x64/stockfish_13_linux_x64")
  File "/home/lezca/.local/lib/python3.9/site-packages/chess/engine.py", line 2824, in popen_uci
    return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
  File "/home/lezca/.local/lib/python3.9/site-packages/chess/engine.py", line 2816, in popen
    return run_in_background(background, name=f"{cls.__name__} (command={command!r})", debug=debug)
  File "/home/lezca/.local/lib/python3.9/site-packages/chess/engine.py", line 201, in run_in_background
    return future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/lezca/.local/lib/python3.9/site-packages/chess/engine.py", line 195, in background
    asyncio.run(coroutine(future))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/lezca/.local/lib/python3.9/site-packages/chess/engine.py", line 2804, in background
    transport, protocol = await Protocol.popen(command, setpgrp=setpgrp, **popen_args)
  File "/home/lezca/.local/lib/python3.9/site-packages/chess/engine.py", line 1214, in popen
    return await asyncio.get_running_loop().subprocess_exec(cls, *command, **popen_args)  # type: ignore
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/victor/stockfish_13_linux_x64/stockfish_13_linux_x64'
Traceback (most recent call last):
  File "/home/lezca/workspace/chipiron/chipiron/src/displays/gui.py", line 106, in mousePressEvent
    piece = self.board.piece_at(square)
AttributeError: 'MainWindow' object has no attribute 'board'
Traceback (most recent call last):
  File "/home/lezca/workspace/chipiron/chipiron/src/displays/gui.py", line 106, in mousePressEvent
    piece = self.board.piece_at(square)
AttributeError: 'MainWindow' object has no attribute 'board'

**Comment by victorgabillon** [comment]
dans chipiron/src/players/boardevaluators/stockfish_evaluation.py
 on demande le chemin de linstall de stockfish
action a faire: 
il faut mettre se chemin en relatif et non absolu
ajouter au requirement d'installer stockfish et renseigner le bon chemin(le faire automatiquement?)
